# Generated by Django 4.1 on 2022-08-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
