# Generated by Django 4.1 on 2022-08-16 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_todos_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.todos')),
            ],
        ),
    ]
